services:
  api:
    build: .
    container_name: api-medico
    ports:
      - "5001:8080"
    depends_on:
      sql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sql,1433;Database=ApiMedico;User Id=sa;Password=ApiMedico123!;TrustServerCertificate=True;
    restart: always

  sql:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    platform: linux/amd64
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ApiMedico123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
    sql_data:
# Comandos útiles:
# Levantar los contenedores en segundo plano:
#   docker compose up --build
# Apagar y eliminar contenedores (no borra los volúmenes):
#   docker-compose down