FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

RUN mkdir -p /docker-entrypoint-initdb.d

COPY ["Scripts BD/init.sql", "/docker-entrypoint-initdb.d/init.sql"]
COPY ["Scripts BD/seed.sql", "/docker-entrypoint-initdb.d/seed.sql"]
COPY ["Scripts BD/entrypoint.sh", "/entrypoint.sh"]

RUN chmod +x /entrypoint.sh && \
    chown mssql:mssql /docker-entrypoint-initdb.d/init.sql /docker-entrypoint-initdb.d/seed.sql /entrypoint.sh

USER mssql

ENTRYPOINT ["/entrypoint.sh"]
